# Generated by Django 3.0.8 on 2020-09-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_auto_20200912_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
