# Generated by Django 3.0.7 on 2020-10-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_auto_20200915_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periorty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='periorty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.Periorty'),
        ),
    ]
