# Generated by Django 3.0.8 on 2020-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0015_auto_20201122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
