# Generated by Django 3.0.8 on 2020-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_auto_20201123_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'date', 'start_time', 'end_time')},
        ),
    ]
