# Generated by Django 3.0.8 on 2020-11-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0017_auto_20201123_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
