# Generated by Django 3.0.8 on 2020-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0019_auto_20201128_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_date',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
