# Generated by Django 3.0.8 on 2020-11-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0020_auto_20201128_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='new_date',
        ),
    ]
