# Generated by Django 3.0.8 on 2020-11-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0022_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
